imports:
    - { resource: config_dev.yml }
    - { resource: parameters.test.yml }

parameters:
    locale: en

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    translator:      { fallbacks: ["%locale%"] }
    default_locale:  "%locale%"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
