#  test config
parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: netpositive_test
    database_user: netpositive52
    database_password: adsdadsfd4546x
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: e2b2faea8490d8771512c3fdc2ef57a6d5157980
